SportBook/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SportBook.Models
{
    public class User
    {
        public int UserId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Nickname { get; set; }
        public string Game_account { get; set; }

        public List<ParticipantList> ParticipantList { get; set; }
        public List<TeamMembers> TeamMembers { get; set; }
        public List<Invitation> Invitations { get; set; }
    }
}

SportBook/Controllers/PlayerListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SportBook.Models;

namespace SportBook.Controllers
{
    public class PlayerListController : Controller, IPlayerList
    {
        private readonly Context _context;

        public PlayerListController(Context context)
        {
            _context = context;
        }
        public IActionResult PlayerListWindow(string filter)
        {
            ViewData["filter"] = filter;

            if (ViewData["filter"] != null)
            {
                ViewData["players"] = getFilteredPlayers(filter);
            }
            else
            {
                ViewData["players"] = getAllPlayers();
            }
            

            return View();
        }
        public List<User> getAllPlayers()
        {
            return _context.Users.ToList();
        }
        public List<User> getFilteredPlayers(string filter)
        {
            return _context.Users.Where(s => s.Username.Contains(filter)).ToList();
        }

        public IActionResult UserProfileWindow(string id)
        {
            ViewData["user"] = id;
            return View();
        }
    }
}

SportBook/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace SportBook.Controllers
{
    public class UserController : Controller
    {
        public IActionResult UserMain()
        {
            return View();
        }
        
        public IActionResult UserProfileWindow()
        {
            return View();
        }
    }
}

SportBook/Views/User/UserMain.cshtml
@{
    ViewData["Title"] = "UserMain";
}

<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container">
        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
            <ul class="navbar-nav flex-grow-1">
                @*<li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="UserMain">User</a>
                    </li>*@

                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="PlayerList" asp-action="PlayerListWindow">Players</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<h1>UserMain</h1>

<style>
    img:hover {
      animation: shake 0.5s;
      animation-iteration-count: infinite;
    }

    @@keyframes shake {
      0% { transform: translate(1px, 1px) rotate(0deg); }
      10% { transform: translate(-1px, -2px) rotate(-1deg); }
      20% { transform: translate(-3px, 0px) rotate(1deg); }
      30% { transform: translate(3px, 2px) rotate(0deg); }
      40% { transform: translate(1px, -1px) rotate(1deg); }
      50% { transform: translate(-1px, 2px) rotate(-1deg); }
      60% { transform: translate(-3px, 1px) rotate(0deg); }
      70% { transform: translate(3px, 1px) rotate(-1deg); }
      80% { transform: translate(-1px, -1px) rotate(1deg); }
      90% { transform: translate(1px, 2px) rotate(0deg); }
      100% { transform: translate(1px, -2px) rotate(-1deg); }
    }
</style>
<body>
    <img src="~/img/header.jpg">
</body>

SportBook/Views/User/UserProfileWindow.cshtml
@{
    ViewData["Title"] = "UserProfileWindow";
}

<h1>UserProfileWindow</h1>